# path to the folder with the labeled data
LABELED_DATA: /home/bar_cohen/Data-Shoham/Labeled-Data-Cleaned

# path to the folder where the dataset should be created in
LOCATION: /home/bar_cohen/KinderGuardian/fast-reid/datasets

# the name that should be given to the dataset
NAME: 1.8.21-dataset

# comma-separated list of labeled data folders that should be included in the corresponding folder
TRAIN: 1.8.21_cam1
TEST: ''
QUERY: ''

# description of the dataset that will be added to the README file
DESCRIPTION: This dataset is used to train a model on the data from 1.8.21 ONLY. The train and test folders are identical and include most of the labeled data from 1.8.21_cam1, except a few images that were used for evaluation of the model by transferring them to the query set.
